export const authConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_FAILURE: " LOGIN_FAILURE",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",

	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
	REGISTER_REQUEST: "REGISTER_REQUEST",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILURE: "REGISTER_FAILURE",
};

export const categoryConstants = {
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
	GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
	GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

	ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
	ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
	ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",

	UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
	UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
	UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",

	DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
	DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
	DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const productConstants = {
	GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
	GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
	GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

	DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
	DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
	DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

	ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
	ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
	ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};

export const initialDataConstants = {
	GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
	GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
	GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const pageConstants = {
	CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
	CREATE_PAGE_SUCCESS: "CREATE_PAGE_SUCCESS",
	CREATE_PAGE_FAILURE: "CREATE_PAGE_FAILURE",
};

export const orderConstants = {
	GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
	GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
	GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

	UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
	UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
	UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const getUsers = {
  GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
};

export const rechargeConstants = {
  GET_ALL_RECHARGE_REQUEST: "GET_ALL_RECHARGE_REQUEST",
  GET_ALL_RECHARGE_SUCCESS: "GET_ALL_RECHARGE_SUCCESS",
  GET_ALL_RECHARGE_FAILURE: "GET_ALL_RECHARGE_FAILURE",

  UPDATE_RECHARGE_REQUEST: "UPDATE_RECHARGE_REQUEST",
  UPDATE_RECHARGE_SUCCESS: "UPDATE_RECHARGE_SUCCESS",
  UPDATE_RECHARGE_FAILURE: "UPDATE_RECHARGE_FAILURE",
};


export const ticketConstants = {
  ADD_NEW_TICKET_REQUEST: "ADD_NEW_TICKET_REQUEST",
  ADD_NEW_TICKET_SUCCESS: "ADD_NEW_TICKET_SUCCESS",
  ADD_NEW_TICKET_FAILURE: "ADD_NEW_TICKET_FAILURE",
};
export const couponConstants = {
	ADD_NEW_COUPON_REQUEST: "ADD_NEW_COUPON_REQUEST",
	ADD_NEW_COUPON_SUCCESS: "ADD_NEW_COUPON_SUCCESS",
	ADD_NEW_COUPON_FAILURE: "ADD_NEW_COUPON_FAILURE",

	GET_ALL_COUPON_REQUEST: "GET_ALL_COUPON_REQUEST",
	GET_ALL_COUPON_SUCCESS: "GET_ALL_COUPON_SUCCESS",
	GET_ALL_COUPON_FAILURE: "GET_ALL_COUPON_FAILURE",

	UPDATE_COUPON_REQUEST: "UPDATE_COUPON_REQUEST",
	UPDATE_COUPON_SUCCESS: "UPDATE_COUPON_SUCCESS",
	UPDATE_COUPON_FAILURE: "UPDATE_COUPON_FAILURE",

	DELETE_COUPON_REQUEST: "DELETE_COUPON_REQUEST",
	DELETE_COUPON_SUCCESS: "DELETE_COUPON_SUCCESS",
	DELETE_COUPON_FAILURE: "DELETE_COUPON_FAILURE",
};